from together import Together
import os
import datetime

# ---------------------------------------------------------
# Configuration Area
# ---------------------------------------------------------
api_key = "tgp_v1_5DGhZ0hxAwmGKuR0WD_TfmoV0FTgWlHoym6h2G3FWJc"
client = Together(api_key=api_key)

base_path = "/Users/alex-lirio-lucian/WaterUse——alex/LLM_Prompting"

# Input: The Unified Report generated by the previous script
input_report = os.path.join(base_path, "Unified_Comparison_Report.md")

# Output 1: Full QA Verdict Report
qa_output = os.path.join(base_path, "QA_Unified_Verdict.md")

# Output 2: The Mistake Book (Appends new errors here)
mistake_book = os.path.join(base_path, "Mistake_Book.md")

# [UPDATED] The Judge Model
# We select Llama-3.3 from your top 3 list as the Judge.
# Why? It is the most robust at following strict formatting instructions (JSON/YAML style) for the mistake log.
judge_model = "meta-llama/Llama-3.3-70B-Instruct-Turbo"


# ---------------------------------------------------------
# Core Logic
# ---------------------------------------------------------
def log_mistake(model_name, version, reason, snippet):
    """
    Appends a failed test case to the Mistake Book.
    """
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    # Create file and header if it doesn't exist
    if not os.path.exists(mistake_book):
        with open(mistake_book, "w", encoding="utf-8") as f:
            f.write("# 📕 Agent Mistake Book (Failure Log)\n")
            f.write("> Records all cases rejected ([NO]) by the AI Judge for future Prompt Engineering.\n\n")

    # Append the mistake
    with open(mistake_book, "a", encoding="utf-8") as f:
        f.write(f"## ❌ Mistake Record [{timestamp}]\n")
        f.write(f"- **Model**: `{model_name}`\n")
        f.write(f"- **Source Version**: {version}\n")
        f.write(f"- **Rejection Reason**: {reason}\n")
        f.write(f"- **Context Snippet**:\n> {snippet[:200]}...\n\n")  # Log first 200 chars
        f.write("---\n\n")


def run_judge():
    print(f"⚖️ Judge Agent [{judge_model}] is entering the court...")

    try:
        with open(input_report, "r", encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        print("❌ Report not found. Please run 'unified_ab_test.py' first.")
        return

    # Evaluation Prompt
    judge_prompt = f"""
    You are a strict QA Judge evaluating an LLM's output for an Agent-Based Model design.

    Here is the full report containing outputs from multiple models (DeepSeek, Llama, Qwen):
    === REPORT START ===
    {content}
    === REPORT END ===

    Your Task:
    1. Analyze EACH output (Old and New for every model).
    2. Rate it as [YES] (Pass) or [NO] (Fail).
    3. Fail Criteria:
       - Symmetric payoff matrices (e.g., 5,5 on diagonals for asymmetric roles).
       - Hallucinated technologies (e.g., pumps, tractors, buying water).
       - Boring/Repetitive game types (e.g., all 4 scenarios are just Prisoner's Dilemma).
       - Ignoring Tipping Points (e.g., no mention of fish collapse).

    Output Format (JSON-like structure for parsing):

    entry:
      model: [Model Name]
      version: [Old or New]
      verdict: [YES or NO]
      reason: [1 sentence explanation]
      snippet: [First 20 words of the bad response]

    (Repeat for all entries found in the text)
    """

    print("   ↳ Judge is reviewing the document (this may take a moment)...")
    response = client.chat.completions.create(
        model=judge_model,
        messages=[{"role": "user", "content": judge_prompt}],
        temperature=0.1
    )

    judgement_text = response.choices[0].message.content

    # Save the full Verdict Report
    with open(qa_output, "w", encoding="utf-8") as f:
        f.write("# ⚖️ Full Judge Verdict\n\n")
        f.write(judgement_text)

    print(f"✅ Verdict Complete! Full report saved to: {qa_output}")

    # --- Simple Parser to extract [NO] verdicts and update Mistake Book ---

    print("📝 Auto-archiving mistakes to Mistake Book...")
    lines = judgement_text.split('\n')
    current_model = "Unknown"
    current_version = "Unknown"

    count = 0
    for i, line in enumerate(lines):
        line = line.strip()
        if "model:" in line.lower():
            current_model = line.split(":", 1)[1].strip()
        if "version:" in line.lower():
            current_version = line.split(":", 1)[1].strip()

        # Check if Verdict is NO
        if "verdict:" in line.lower() and "[no]" in line.lower():
            # Attempt to parse Reason and Snippet from following lines
            reason = "Reason not parsed"
            snippet = "N/A"

            # Look ahead a few lines
            for j in range(i + 1, min(i + 5, len(lines))):
                if "reason:" in lines[j].lower():
                    reason = lines[j].split(":", 1)[1].strip()
                if "snippet:" in lines[j].lower():
                    snippet = lines[j].split(":", 1)[1].strip()

            # Write to Mistake Book
            log_mistake(current_model, current_version, reason, snippet)
            count += 1

    if count > 0:
        print(f"📕 Archived {count} failures to 'Mistake_Book.md'.")
    else:
        print("🎉 Perfect! The Judge found no obvious failures (or parsing didn't match).")


if __name__ == "__main__":
    run_judge()