from together import Together
import os

# 1. Insert your API Key (Remember to revoke it after your experiments are done)
api_key = "tgp_v1_5DGhZ0hxAwmGKuR0WD_TfmoV0FTgWlHoym6h2G3FWJc"
client = Together(api_key=api_key)

# 2. Absolute path configuration (Ensures 100% path resolution)
input_md_path = "/LLM_Prompting/all_models_comparison.md"
output_report_path = "/LLM_Prompting/QA_Evaluation_All_Judges.md"


def evaluate_models_with_all_judges():
    print("🔍 Reading the merged report to be evaluated...")

    try:
        with open(input_md_path, "r", encoding="utf-8") as f:
            generated_content = f.read()
    except FileNotFoundError:
        print(f"❌ File not found at {input_md_path}. Please check the path.")
        return

    # 3. The Strict 4-Step QA Prompt for the LLM Judges
    evaluation_prompt = f"""
    You are an expert Institutional Analyst and Game Theory Reviewer. 
    Your task is to evaluate a set of Action Situations and Payoff Matrices generated by different AI models.

    Here is the Markdown file containing the models' outputs:
    === BEGIN GENERATED CONTENT ===
    {generated_content}
    === END GENERATED CONTENT ===

    Please review the outputs of EACH MODEL in the text using the following strict 4-Step QA Criteria:

    1. **Asymmetry Test**: Payoff matrices MUST NOT be completely symmetric. Upstream farmers (UF) and Downstream farmers (DF) have different impacts. If a matrix has perfectly mirrored payoffs (e.g., 5,5 and 3,3 on diagonals) for an asymmetric situation, it fails.
    2. **Physical Constraints Test**: Look for hallucinations. The maximum irrigated fields is 10. There are no advanced technologies (like water pumps or tractors) mentioned in the ODD+D. If they invent constraints or actions, it fails.
    3. **Diversity Test**: The model must provide distinct game-theoretic dilemmas (e.g., Tragedy of the Commons, Stag Hunt, Trust Game). If all situations are just "Prisoner's Dilemma" with different names, it fails.
    4. **Terminology Test**: The model should accurately use ODD+D specific terms like "July inflow memory", "Larvae", or "National Authority" in its rationale.

    ### Output Format Requirements:
    For each model evaluated, provide:
    - **Model Being Evaluated**: (Name of the model being judged)
    - **Overall Verdict**: [YES] or [NO]
    - **Step 1 (Asymmetry)**: Pass/Fail + 1 sentence why.
    - **Step 2 (Constraints)**: Pass/Fail + 1 sentence why.
    - **Step 3 (Diversity)**: Pass/Fail + 1 sentence why.
    - **Step 4 (Terminology)**: Pass/Fail + 1 sentence why.
    - **Best Action Situation**: Mention which specific Action Situation from this model is the highest quality and worth keeping.
    """

    # 4. Define the three 'Judge' models
    judges = [
        "deepseek-ai/DeepSeek-R1",
        "deepseek-ai/DeepSeek-V3",
        "meta-llama/Llama-3.3-70B-Instruct-Turbo"
    ]

    print(f"🚀 Starting [Multi-Model Cross-Evaluation]. Results will be saved to: {output_report_path}\n")

    # Open the output file in write mode to start fresh, it stays open during the loop
    with open(output_report_path, "w", encoding="utf-8") as out_file:
        # Write the Markdown header for the report
        out_file.write("# ⚖️ Ultimate QA Court: Tri-Model Cross-Evaluation Report\n\n")
        out_file.write(
            "> This report features three top-tier AI models acting as judges, strictly evaluating the generated game-theoretic matrices based on a 4-step rubric.\n\n")

        for judge_name in judges:
            print(f"⏳ Judge [{judge_name}] is now reviewing (this may take 1-2 minutes)...")
            try:
                # API Call to the Judge Model
                response = client.chat.completions.create(
                    model=judge_name,
                    messages=[
                        {"role": "system",
                         "content": "You are a ruthless, highly accurate peer reviewer for game theory papers."},
                        {"role": "user", "content": evaluation_prompt}
                    ],
                    temperature=0.3  # Low temperature for consistent and analytical evaluation
                )

                evaluation_result = response.choices[0].message.content

                # Append the judge's verdict to the Markdown file
                out_file.write(f"## 🧑‍⚖️ Chief Judge: `{judge_name}`'s Verdict\n")
                out_file.write("---\n\n")
                out_file.write(evaluation_result)
                out_file.write("\n\n<br><br>\n\n")  # Visual separation between judges

                print(f"✅ Judge [{judge_name}] has completed the evaluation!")

            except Exception as e:
                # Handle API timeouts or errors gracefully without crashing the whole script
                print(f"❌ Judge [{judge_name}] encountered an error: {e}")
                out_file.write(f"## 🧑‍⚖️ Chief Judge: `{judge_name}`\n\n**Evaluation Failed**: {e}\n\n---\n\n")

    print(
        f"\n🎉 Cross-evaluation complete! Open `{output_report_path}` in VS Code to see which model achieved a consensus [YES]!")


if __name__ == "__main__":
    evaluate_models_with_all_judges()